apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
annotations:
  "service.beta.kubernetes.io/aws-load-balancer-security-groups": {{ .Values.elbSecurityGroup}}
spec:
  selector:
    app.kubernetes.io/name: {{ template "service.name" . }}
  ports:
    - port: 8000
      targetPort: http
  type: LoadBalancer

  