kind: Namespace
apiVersion: v1
metadata:
    name: anz-assessment
    labels: 
      name: anz-assessment
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: anz-assessment
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: anz-assessment
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: anz-assessment
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: anz-assessment
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
