FROM golang:alpine
ENV GO111MODULE=on
WORKDIR /app
ADD ./ /app
RUN apk update --no-cache
RUN apk add git
RUN go get rsc.io/quote/v3
RUN go get github.com/gorilla/mux
RUN go build -o golang-test .
ENTRYPOINT ["./app/golang-test"]
EXPOSE 8000
